alter table UNTITLED140_REQUEST add constraint FK_UNTITLED140_REQUEST_ON_INITIATOR foreign key (INITIATOR_ID) references SEC_USER(ID);
create index IDX_UNTITLED140_REQUEST_ON_INITIATOR on UNTITLED140_REQUEST (INITIATOR_ID);
