alter table UNTITLED140_CFO_LINE add constraint FK_UNTITLED140_CFO_LINE_ON_CFO foreign key (CFO_ID) references UNTITLED140_CFO(ID);
alter table UNTITLED140_CFO_LINE add constraint FK_UNTITLED140_CFO_LINE_ON_EXPENCE_ITEM foreign key (EXPENCE_ITEM_ID) references UNTITLED140_EXPENCE_ITEM(ID);
create index IDX_UNTITLED140_CFO_LINE_ON_CFO on UNTITLED140_CFO_LINE (CFO_ID);
create index IDX_UNTITLED140_CFO_LINE_ON_EXPENCE_ITEM on UNTITLED140_CFO_LINE (EXPENCE_ITEM_ID);
